export const seatData = [
    { id: 1, isBooked: false },
    { id: 2, isBooked: false },
    { id: 3, isBooked: false },
    { id: 4, isBooked: false },
    { id: 5, isBooked: false },
    { id: 6, isBooked: false },
    { id: 7, isBooked: false },
    { id: 8, isBooked: false },
    { id: 9, isBooked: false },
    { id: 10, isBooked: false },
    { id: 11, isBooked: false },
    { id: 12, isBooked: false },
    { id: 13, isBooked: false },
    { id: 14, isBooked: false },
    { id: 15, isBooked: false },
];
